### ISSUE TITLE
GeneralTransformer applied to DPGAN and PATEGAN is potentially broken

### ISSUE THREAD

**Issue by HarrisonWilde** [opendp/smartnoise-sdk#333] opened 2021-02-03 12:35 UTC
Hi, I have been playing around with DPCTGAN, DPGAN, PATECTGAN and PATEGAN and noticed that for a simple input like some samples from a Gaussian Mixture Model, the DPCTGAN and PATECTGAN do fine in learning and generating synthetic data very quickly (after just a couple of epochs), meanwhile the DPGAN and PATEGAN do correctly produce data around the right modes, but with some type of bias that I can observe, and seems to change depending on the transformer I use. I notice that the DPCTGAN and PATECTGAN don't have a transformer passed but instead use the DataTransformer imported from the CTGAN package (an old version, have to go back to 0.2.2.dev1 to get this to work), and these seem to work fine. I tried swapping the Transformer passed to the DPGAN and PATEGAN to this but to no success. See here some real data from a GMM:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/35736580/106747268-941cd600-661b-11eb-9c2b-88426dfd5928.png">

Then some data generated by the DPCTGAN:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/35736580/106747540-f675d680-661b-11eb-897a-075153f72dab.png">

Looks fine, and finally some data generated by the DPGAN with identical parameters (the uniformity of the bias suggests to me that this is indeed some problem with data transformation):

<img width="752" alt="image" src="https://user-images.githubusercontent.com/35736580/106747837-52405f80-661c-11eb-94fa-5d831088225d.png">

Happy to try and help how I can, this is all using the models as configured in your repo, tabular data on inspection seems ok from DPGAN and PATEGAN, but I would be suspicious of all their outputs as a result as it is not so easy to spot these things in higher dimensions.

**Comment by eedeleon** [comment] 2021-02-04 00:45
Thanks for bringing this to our attention!

Very interesting findings, the graphs are so clear and concise at sharing the finding.

I think there are a few approaches to narrowing down the source of the issue. The most straightforward would be to have an option of changing the Data Transformer to see if the same difference appears without different data transformations. We had some nuances lead us to different base transformations but we may be able to circumvent those nuances.

In general we might learn a bit more if we try to reproduce this with categorical vs continuous data. We have seen performance across synthesizers show better results for different data types. https://arxiv.org/pdf/2011.05537.pdf for example, showed MWEM performed better for categorical data than continues etc. 

Let me know if you have some ideas for possible collaborations. If not and you would prefer we share some options we can discuss over this issue or maybe setup a call to figure out how to address this discrepancy.

**Comment by HarrisonWilde** [comment] 2021-02-04 12:46
Happy to call at some point about this, I am not sure I have the bandwidth (or indeed the knowledge) to do all of the testing that I can imagine might be required, but if we could have a discussion around the transformer as it stands, perhaps first how we might intentionally perturb the inputs and subsequently outputs via the transformer to see if this is reflected in similar density plots, we could go from there?

**Comment by eedeleon** [comment] 2021-02-20 20:43
It looks like there is an issue with this code path that may be related to a privacy leak with our use of GMM. We added an exception to avoid it and will be evaluating and updating our preprocessing layer soon once we have a validated fix

**Comment by joshua-oss** [comment] 2021-11-20 05:33
We discovered some paths that were evading the check for GMM.  GMM is now disabled on all synthesizers.  Closing this issue:

#433
#432

**Closed by joshua-oss** 2021-11-20 05:33 UTC
Labels: bug, Priority 1: High
