### ISSUE TITLE
Panda privacy reader produces SQL with syntax error

### ISSUE THREAD

**Issue by saisaravanan** [opendp/smartnoise-sdk#330] opened 2021-01-13 20:44 UTC
When checking out latest code from smartnoise-sdk and core packages as on Jan 12th returns a SQL syntax exception when trying to run queries using pandas reader wrapped in privacy reader. I did a pip install using git https url since PyPi package was not giving the latest code. Tried different code samples from smartnoise-samples and reproduced same error with PandasReader. SparkReader queries seem to be working fine. 

### Error message for the code sample below : 

``OperationalError: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT pid ) AS keycount, married AS married, SUM ( income ) AS sum_income, COUNT ( income ) AS count_income, COUNT ( * ) AS count_0xd8ce FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY pid ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT pid AS pid, married AS married, CASE WHEN income < 0 THEN 0 WHEN income > 500000 THEN 500000 ELSE  income END AS income FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1 GROUP BY married]
(Background on this error at: http://sqlalche.me/e/13/e3q8)``

### Code Sample used:
```

import pandas as pd
from opendp.smartnoise.sql import PandasReader, PrivateReader
from opendp.smartnoise.metadata import CollectionMetadata

pums = pd.read_csv('PUMS.csv')
meta = CollectionMetadata.from_file('PUMS.yaml')

query = 'SELECT married, AVG(income) AS income, COUNT(*) AS n FROM PUMS.PUMS GROUP BY married'

reader = PandasReader(meta, pums)
private_reader = PrivateReader(meta, reader)

result = private_reader.execute_df(query)
print(result)
```

**Full stack trace**
```
PandaSQLException                         Traceback (most recent call last)
<ipython-input-1-27512490a182> in <module>
     11 private_reader = PrivateReader(meta, reader)
     12 
---> 13 result = private_reader.execute_df(query)
     14 print(result)

/workplace/opendp/venv/src/opendp-smartnoise/sdk/opendp/smartnoise/reader/base.py in execute_df(self, query)
     25             raise ValueError("Please pass a string to this function.")
     26 
---> 27         return self._to_df(self.execute(query))

/workplace/opendp/venv/src/opendp-smartnoise/sdk/opendp/smartnoise/sql/private_reader.py in execute(self, query_string)
    152         """
    153         query = self.parse_query_string(query_string)
--> 154         return self._execute_ast(query)
    155 
    156     def _execute_ast(self, query, cache_exact=False):

/workplace/opendp/venv/src/opendp-smartnoise/sdk/opendp/smartnoise/sql/private_reader.py in _execute_ast(self, query, cache_exact)
    215             self.cached_exact = None
    216             self.cached_ast = None
--> 217             db_rs = self._get_reader(subquery)._execute_ast(subquery)
    218 
    219         clamp_counts = self._options.clamp_counts

/workplace/opendp/venv/src/opendp-smartnoise/sdk/opendp/smartnoise/sql/reader/base.py in _execute_ast(self, query)
     17         else:
     18             query_string = str(query)
---> 19         return self.execute(query_string)
     20 
     21     def _execute_ast_df(self, query):

/workplace/opendp/venv/src/opendp-smartnoise/sdk/opendp/smartnoise/sql/reader/pandas.py in execute(self, query)
    111 
    112         df_for_diffpriv1234 = self.df
--> 113         q_result = sqldf(clean_query(query), locals())
    114         return [tuple([col for col in q_result.columns])] + [val[1:] for val in q_result.itertuples()]

/workplace/opendp/venv/lib/python3.7/site-packages/pandasql/sqldf.py in sqldf(query, env, db_uri)
    154     >>> sqldf("select avg(x) from df;", locals())
    155     """
--> 156     return PandaSQL(db_uri)(query, env)

/workplace/opendp/venv/lib/python3.7/site-packages/pandasql/sqldf.py in __call__(self, query, env)
     61                 result = read_sql(query, conn)
     62             except DatabaseError as ex:
---> 63                 raise PandaSQLException(ex)
     64             except ResourceClosedError:
     65                 # query returns nothing

PandaSQLException: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT pid ) AS keycount, married AS married, SUM ( income ) AS sum_income, COUNT ( income ) AS count_income, COUNT ( * ) AS count_0xd8ce FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY pid ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT pid AS pid, married AS married, CASE WHEN income < 0 THEN 0 WHEN income > 500000 THEN 500000 ELSE  income END AS income FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1 GROUP BY married]
```

**Comment by joshua-oss** [comment] 2021-01-14 19:03
This error comes from an attempt to use an older version of SQLite which doesn't support `SELECT DISTINCT`.  To work around this issue, you can update to a recent version of anaconda or miniconda; both include a much newer SQLite.  Another workaround would be to use `row_privacy`, since the `DISTINCT` modifier is only used to enforce `max_contrib`.  But the preference would be to ensure using a more recent SQLite.

We have checked in a fix to provide a more useful error message when older SQLite is encountered, which should be migrating to PyPi soon.

**Comment by eedeleon** [comment] 2021-01-15 23:57
We updated pypi with the latest changes https://pypi.org/project/opendp-smartnoise/0.1.2/

**Comment by eedeleon** [comment] 2021-01-22 07:34
For our builds, which are testing against the pypi bits

conda install --yes -c anaconda sqlite

Installs the correct version of sqlite.

**Comment by saisaravanan** [comment] 2021-01-28 22:54
Thanks for the update. Will try upgrading to later version of sqlite.

**Comment by joshua-oss** [comment] 2021-05-25 00:13
Confirmed fixed

**Closed by joshua-oss** 2021-05-25 00:13 UTC
