### ISSUE TITLE
snsql.from_df error

### ISSUE THREAD

**Issue by ir1369** [opendp/smartnoise-sdk#528] opened 2023-01-31 11:20 UTC
hi.
I got this error:
![image](https://user-images.githubusercontent.com/55793180/215746279-d71848b1-1ca2-4977-b63e-0e3bea981b7d.png)

**Comment by joshua-oss** [comment] 2023-02-05 03:27
Hi there, I am unable to reproduce this behavior in a new Python 3.9 instance, using this code:

```python
import pandas as pd
from snsql import Privacy, from_df

privacy = Privacy(epsilon=1.0, delta=1e-10)
meta = "../datasets/PUMS.yaml"
pums = pd.read_csv("../datasets/PUMS.csv")

reader = from_df(pums, metadata=meta, privacy=privacy)

q = "SELECT sex as educ, educ as sex, COUNT(*) AS n FROM PUMS.PUMS GROUP BY sex, educ HAVING sex > 2"
res = reader.execute(q)
```

However, if I drop the `age` column from PUMS, I get the same error:

```python
pums = pd.read_csv("../datasets/PUMS.csv")
pums.drop(columns=["age"], inplace=True)
reader = from_df(pums, metadata=meta, privacy=privacy)
```

Can you verify if your CSV file has all the same columns as are referenced in the YAML?  Note that you can remove columns from the YAML if you don't want to use them in the CSV.

**Comment by joshua-oss** [comment] 2023-05-11 00:27
Closing as not reproducible.  This is probably a missing field in YAML.  Please re-open if needed.

**Closed by joshua-oss** 2023-05-11 00:27 UTC
